baseURL = 'https://blog.bowen-song.top/'
languageCode = 'zh-cn'
title = "Bowen's Blog"
theme = "hugo-bearcub"
copyright = "Bowen Song (CC by 4.0)"

enableRobotsTXT = true

[author]
  name = "Bowen Song"

[params]
  description = "Where I drop my shit"
  title = "Bowen's Blog"
  dateFormat = "2006-01-02"
  madeWith = "Made with [Hugo](https://gohugo.io/) x [Bear Cub](https://github.com/clente/hugo-bearcub)"

[social]
  email = "songbowen1229@gmail.com"

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'
